"""add client contact

Revision ID: b51bd073d823
Revises: eb85eddf42fd
Create Date: 2026-06-01 17:04:50.325358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b51bd073d823'
down_revision: Union[str, Sequence[str], None] = 'eb85eddf42fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('seller', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('seller', 'zip_code',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('shipment', sa.Column('client_contact_email', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipment', 'client_contact_email')
    op.alter_column('seller', 'zip_code',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('seller', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
