"""change client contact to str

Revision ID: c1f89b326194
Revises: 97312dc6dd1d
Create Date: 2026-06-08 15:06:51.762516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'c1f89b326194'
down_revision: Union[str, Sequence[str], None] = '97312dc6dd1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipment', sa.Column('client_contact_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('shipment', 'client_contact_email',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shipment', 'client_contact_email',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.INTEGER(),
               nullable=True)
    op.drop_column('shipment', 'client_contact_phone')
    # ### end Alembic commands ###
